# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-23 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_set_min_template_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commontmplperm',
            options={'verbose_name': '\u516c\u5171\u6d41\u7a0b\u6a21\u677f\u6743\u9650 CommonTmplPerm', 'verbose_name_plural': '\u516c\u5171\u6d41\u7a0b\u6a21\u677f\u6743\u9650 CommonTmplPerm'},
        ),
    ]
