# Generated by Django 2.2.24 on 2021-09-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultTemplateScheme",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(default=-1, help_text="项目ID，-1代表公共流程")),
                ("template_id", models.IntegerField(help_text="流程ID")),
                ("default_scheme_ids", models.TextField(blank=True, help_text="默认执行方案组合ID拼接结果，用`,`分隔", null=True)),
            ],
            options={"verbose_name": "默认执行方案", "unique_together": {("project_id", "template_id")},},
        ),
    ]
