# Generated by Django 2.2.24 on 2021-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clocked_task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clockedtask",
            name="plan_start_time",
            field=models.DateTimeField(db_index=True, help_text="计划任务启动时间"),
        ),
        migrations.AlterField(
            model_name="clockedtask", name="task_id", field=models.IntegerField(help_text="taskflow 任务 ID", null=True),
        ),
    ]
