# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0028_auto_20201227_1952"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineinstance",
            name="is_expired",
            field=models.BooleanField(default=False, help_text="运行时被定期清理即为过期", verbose_name="是否已经过期"),
        ),
        migrations.AlterField(
            model_name="pipelineinstance",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
        ),
    ]
