# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-19 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20181228_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
