# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20190729_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.HistoryData'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.ProcessSnapshot'),
        ),
    ]
