!!python/unicode 'language': python
app_code: bk_sops
app_name: 标准运维
is_use_celery: True
author: 蓝鲸智云
introduction: 标准运维是通过一套成熟稳定的任务调度引擎，把在多系统间的工作整合到一个流程，助力运维实现跨系统调度自动化的SaaS应用。
version: 3.3.13
category: 运维工具
language_support: 中文
desktop:
  width: 1280
  height: 720
  is_max: True
container:
    memory: 2048
