codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 50%
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 1%
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: false       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]
