# Generated by Django 2.2.24 on 2021-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserConf",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
                ("project_id", models.IntegerField(verbose_name="所属项目ID")),
                ("tasktmpl_ordering", models.CharField(default="-id", max_length=255, verbose_name="模板列表默认排序字段")),
            ],
        ),
    ]
