# Generated by Django 2.2.16 on 2021-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_migrate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="migratelog",
            name="finished",
        ),
        migrations.RemoveField(
            model_name="migratelog",
            name="migrated",
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componenetExecuteData_count",
            field=models.IntegerField(default=0, verbose_name="componentExecute数据总量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componenetExecuteData_finished",
            field=models.IntegerField(default=False, verbose_name="componentExecute迁移状态"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componenetExecuteData_migrated",
            field=models.IntegerField(default=0, verbose_name="componentExecute已迁移量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componentInTemplate_count",
            field=models.IntegerField(default=0, verbose_name="component数据总量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componentInTemplate_finished",
            field=models.IntegerField(default=False, verbose_name="component迁移状态"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="componentInTemplate_migrated",
            field=models.IntegerField(default=0, verbose_name="component已迁移量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="instanceInPipeline_count",
            field=models.IntegerField(default=0, verbose_name="instance数据总量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="instanceInPipeline_finished",
            field=models.IntegerField(default=False, verbose_name="instance迁移状态"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="instanceInPipeline_migrated",
            field=models.IntegerField(default=0, verbose_name="instance已迁移量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="templateInPipeline_count",
            field=models.IntegerField(default=0, verbose_name="template数据总量"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="templateInPipeline_finished",
            field=models.IntegerField(default=False, verbose_name="template迁移状态"),
        ),
        migrations.AddField(
            model_name="migratelog",
            name="templateInPipeline_migrated",
            field=models.IntegerField(default=0, verbose_name="template已迁移量"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="componenetExecuteData_end",
            field=models.IntegerField(default=1000, verbose_name="componentExecute迁移终点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="componentExecuteData_start",
            field=models.IntegerField(default=1, verbose_name="componentExecute迁移起点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="componentInTemplate_end",
            field=models.IntegerField(default=1000, verbose_name="component迁移终点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="componentInTemplate_start",
            field=models.IntegerField(default=1, verbose_name="componet迁移起点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="instanceInPipeline_end",
            field=models.IntegerField(default=1000, verbose_name="instance迁移终点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="instanceInPipeline_start",
            field=models.IntegerField(default=1, verbose_name="instance迁移起点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="templateInPipeline_end",
            field=models.IntegerField(default=1000, verbose_name="template迁移终点"),
        ),
        migrations.AlterField(
            model_name="migratelog",
            name="templateInPipeline_start",
            field=models.IntegerField(default=1, verbose_name="template迁移起点"),
        ),
    ]
