# Generated by Django 3.2.13 on 2023-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallbackRetryTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.BigIntegerField(verbose_name="提单人")),
                ("node_id", models.CharField(blank=True, default="", max_length=255, verbose_name="任务实例节点ID")),
                ("version", models.CharField(max_length=256, verbose_name="版本")),
                ("data", models.JSONField(default=dict, verbose_name="callback Data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "准备回调"),
                            ("SUCCESS", "回调成功"),
                            ("FAILED", "回调失败"),
                            ("REVOKED", "已取消"),
                            ("DISCARDED", "丢弃"),
                        ],
                        default="READY",
                        max_length=32,
                        verbose_name="回调状态",
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="回调次数")),
                ("error", models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name="异常信息")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("finish_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
            ],
            options={
                "verbose_name": "回调重试任务",
                "verbose_name_plural": "回调重试任务表",
                "index_together": {("task_id", "node_id", "version", "status")},
            },
        ),
    ]
