# Generated by Django 2.2.24 on 2021-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserCustomProjectConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
                ("project_id", models.IntegerField(verbose_name="所属项目ID")),
                ("task_template_ordering", models.CharField(default="-id", max_length=255, verbose_name="模板列表默认排序字段")),
            ],
            options={
                "index_together": {("username", "project_id")},
            },
        ),
    ]
