# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('flow', '项目流程'), ('common_flow)', '公共流程'), ('periodic_task', '周期任务'), ('mini_app', '轻应用')], max_length=255, verbose_name='收藏对象类型'),
        ),
    ]
