# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_auto_20200907_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection", name="instance_id", field=models.IntegerField(default=-1, verbose_name="收藏对象ID"),
        ),
        migrations.AlterIndexTogether(name="collection", index_together=set([("category", "instance_id")]),),
    ]
