# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 14:29
from __future__ import unicode_literals

from django.db import migrations
import json


def load_instance_id(apps, schema_editor):
    collection_model = apps.get_model("collection", "Collection")
    for row in collection_model.objects.all():
        extra_info = json.loads(row.extra_info)
        row.instance_id = extra_info.get("id")
        row.save(update_fields=["instance_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_auto_20201103_2229"),
    ]

    operations = [migrations.RunPython(load_instance_id, reverse_code=migrations.RunPython.noop)]
