# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_add_instance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection", name="instance_id", field=models.IntegerField(verbose_name="收藏对象ID"),
        ),
    ]
