# Generated by Django 4.2.17 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_auto_20201103_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="category",
            field=models.CharField(
                choices=[
                    ("project", "项目"),
                    ("flow", "项目流程"),
                    ("common_flow", "公共流程"),
                    ("periodic_task", "周期任务"),
                    ("mini_app", "轻应用"),
                ],
                max_length=255,
                verbose_name="收藏对象类型",
            ),
        ),
    ]
