apiVersion: bkai.tencent.com/v1
kind: Skill
metadata:
  code: bk-sops-analyze-task-error
  name: 标准运维任务失败分析 Skill
  version: "1.0.0"
  description: 分析任务失败
spec:
  generate_type: space
  is_public: true
  tag_names: []