# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xbaIP')),
                ('os', models.CharField(max_length=100, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('partition', models.CharField(max_length=100, verbose_name=b'\xe5\x88\x86\xe5\x8c\xba')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a',
            },
        ),
    ]
