# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_diskusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskusage',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DiskUsage', to='home_application.Host'),
            preserve_default=False,
        ),
    ]
