# Generated by Django 2.2.16 on 2021-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktmpl3", "0018_auto_20210319_1752"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="default_flow_type",
            field=models.CharField(
                choices=[("common", "默认任务流程"), ("common_func", "职能化任务流程")],
                default="common",
                max_length=255,
                verbose_name="偏好任务流程类型",
            ),
        ),
    ]
