# Generated by Django 3.2.13 on 2023-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktmpl3", "0019_tasktemplate_default_flow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="draft_template_id",
            field=models.IntegerField(null=True, verbose_name="草稿对应的模板id"),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="published",
            field=models.BooleanField(default=True, verbose_name="是否是已发布状态"),
        ),
    ]
