# Generated by Django 3.2.25 on 2026-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktmpl3", "0019_tasktemplate_default_flow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="ai_notify_group",
            field=models.JSONField(default=dict, verbose_name="AI分析群聊通知配置"),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="ai_notify_type",
            field=models.JSONField(default=dict, verbose_name="AI分析个人通知方式"),
        ),
    ]
