# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow3', '0005_taskflowinstance_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflowinstance',
            name='template_source',
            field=models.CharField(choices=[(b'project', '\u9879\u76ee\u6d41\u7a0b'), (b'common', '\u516c\u5171\u6d41\u7a0b')], default=b'project', max_length=32, verbose_name='\u6d41\u7a0b\u6a21\u677f\u6765\u6e90'),
        ),
    ]
