# Generated by Django 2.2.6 on 2021-04-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0013_auto_20210125_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskflowinstance",
            name="engine_ver",
            field=models.IntegerField(choices=[(1, "v1"), (2, "v2")], default=1, verbose_name="引擎版本"),
        ),
    ]
