# Generated by Django 2.2.6 on 2021-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0013_auto_20210125_1943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskflowinstance",
            name="category",
            field=models.CharField(
                choices=[
                    ("OpsTools", "运维工具"),
                    ("MonitorAlarm", "监控告警"),
                    ("ConfManage", "配置管理"),
                    ("DevTools", "开发工具"),
                    ("EnterpriseIT", "企业IT"),
                    ("OfficeApp", "办公应用"),
                    ("Other", "其它"),
                    ("Default", "默认分类"),
                ],
                default="Default",
                max_length=255,
                verbose_name="任务类型，继承自模板",
            ),
        ),
    ]
