# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0013_auto_20200907_1754"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskOperationTimesConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(verbose_name="项目 ID")),
                (
                    "operation",
                    models.CharField(
                        choices=[("start", "启动"), ("pause", "暂停"), ("resume", "恢复"), ("revoke", "撤销")],
                        max_length=64,
                        verbose_name="任务操作",
                    ),
                ),
                ("times", models.IntegerField(verbose_name="限制操作次数")),
                (
                    "time_unit",
                    models.CharField(
                        choices=[("m", "分钟"), ("h", "小时"), ("d", "天")], max_length=10, verbose_name="限制时间单位"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务操作次数限制配置 TaskOperationTimesConfig",
                "verbose_name_plural": "任务操作次数限制配置 TaskOperationTimesConfig",
            },
        ),
        migrations.AlterUniqueTogether(
            name="taskoperationtimesconfig", unique_together=set([("project_id", "operation")]),
        ),
    ]
