# Generated by Django 2.2.6 on 2021-04-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0014_auto_20210319_1757"),
        ("taskflow3", "0014_taskflowinstance_engine_ver"),
    ]

    operations = []
