# Generated by Django 2.2.16 on 2021-05-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0014_auto_task_threshold"),
        ("taskflow3", "0015_merge_20210408_1926"),
    ]

    operations = []
