# Generated by Django 2.2.24 on 2021-12-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0017_auto_20211116_1526"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autoretrynodestrategy",
            options={
                "verbose_name": "节点自动重试策略 AutoRetryNodeStrategy",
                "verbose_name_plural": "节点自动重试策略 AutoRetryNodeStrategy",
            },
        ),
        migrations.CreateModel(
            name="TimeoutNodeConfig",
            fields=[
                ("task_id", models.BigIntegerField(verbose_name="taskflow id")),
                ("root_pipeline_id", models.CharField(max_length=64, verbose_name="root pipeline id")),
                (
                    "action",
                    models.CharField(
                        choices=[("forced_fail", "强制失败"), ("forced_fail_and_skip", "强制失败并跳过")],
                        max_length=32,
                        verbose_name="action",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name="task node id"),
                ),
                ("timeout", models.IntegerField(verbose_name="node timeout time")),
            ],
            options={
                "verbose_name": "节点超时配置 TimeoutNodeConfig",
                "verbose_name_plural": "节点超时配置 TimeoutNodeConfig",
                "index_together": {("root_pipeline_id", "node_id")},
            },
        ),
    ]
