# Generated by Django 3.2.12 on 2022-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0020_autoretrynodestrategy_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskflowinstance",
            name="recorded_executor_proxy",
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="任务执行人代理"),
        ),
        migrations.AlterField(
            model_name="taskflowinstance",
            name="engine_ver",
            field=models.IntegerField(choices=[(1, "v1"), (2, "v2")], default=2, verbose_name="引擎版本"),
        ),
    ]
