# Generated by Django 3.2.13 on 2022-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0022_taskcallbackrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskFlowRelation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.BigIntegerField(db_index=True, verbose_name="任务ID")),
                ("parent_task_id", models.BigIntegerField(db_index=True, verbose_name="父任务ID")),
                ("root_task_id", models.BigIntegerField(db_index=True, verbose_name="根任务ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={"verbose_name": "任务关系", "verbose_name_plural": "任务关系",},
        ),
        migrations.AddField(
            model_name="taskflowinstance",
            name="is_child_taskflow",
            field=models.BooleanField(default=False, verbose_name="是否为子任务"),
        ),
    ]
