# Generated by Django 3.2.13 on 2022-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0023_auto_20220809_2112"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_id", models.IntegerField(verbose_name="范围对象ID")),
                ("scope", models.IntegerField(choices=[(1, "project"), (2, "template")], verbose_name="配置范围")),
                ("config_type", models.IntegerField(choices=[(1, "subprocess")], verbose_name="配置类型")),
                (
                    "config_value",
                    models.CharField(
                        choices=[
                            ("enable_independent_subprocess", "启用独立子流程"),
                            ("disable_independent_subprocess", "禁用独立子流程"),
                        ],
                        max_length=512,
                        verbose_name="配置值",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务配置 TaskConfig",
                "verbose_name_plural": "任务配置 TaskConfig",
                "ordering": ["-id"],
                "index_together": {("scope", "scope_id", "config_type")},
            },
        ),
    ]
