# Generated by Django 3.2.25 on 2026-08-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskflow3", "0025_auto_20230104_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskconfig",
            name="config_type",
            field=models.IntegerField(
                choices=[(1, "subprocess"), (2, "retry_params"), (3, "active_callback")], verbose_name="配置类型"
            ),
        ),
        migrations.AlterField(
            model_name="taskconfig",
            name="config_value",
            field=models.CharField(
                choices=[
                    ("enable_independent_subprocess", "启用独立子流程"),
                    ("disable_independent_subprocess", "禁用独立子流程"),
                    ("enable_fill_retry_params", "启用节点重试填参"),
                    ("disable_fill_retry_params", "禁用节点重试填参"),
                    ("enable_active_callback", "启用回调兜底接管"),
                    ("disable_active_callback", "禁用回调兜底接管"),
                ],
                max_length=512,
                verbose_name="配置值",
            ),
        ),
    ]
