# Generated by Django 3.2.15 on 2024-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateSharedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("market_record_id", models.CharField(db_index=True, max_length=32, verbose_name="模板市场记录 ID")),
                ("project_id", models.IntegerField(help_text="项目 ID", verbose_name="项目 ID")),
                ("templates", models.JSONField(help_text="模板 ID 列表", verbose_name="模板 ID 列表")),
                ("creator", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("extra_info", models.JSONField(blank=True, null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "模板共享记录 TemplateSharedRecord",
                "verbose_name_plural": "模板共享记录 TemplateSharedRecord",
            },
        ),
    ]
