# Generated by Django 3.2.15 on 2024-12-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateSharedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(default=-1, help_text="项目 ID", verbose_name="项目 ID")),
                ("template_id", models.IntegerField(db_index=True, help_text="模板 ID", verbose_name="模板 ID")),
                ("creator", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("extra_info", models.JSONField(blank=True, null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "模板共享记录 TemplateSharedRecord",
                "verbose_name_plural": "模板共享记录 TemplateSharedRecord",
            },
        ),
    ]
