# Generated by Django 2.2.16 on 2021-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="color",
            field=models.CharField(default="#dcffe2", help_text="标签颜色值", max_length=7, verbose_name="标签颜色"),
        ),
        migrations.AlterField(
            model_name="label",
            name="creator",
            field=models.CharField(help_text="标签创建人", max_length=255, verbose_name="创建者"),
        ),
        migrations.AlterField(
            model_name="label",
            name="description",
            field=models.CharField(blank=True, help_text="标签描述", max_length=255, null=True, verbose_name="标签描述"),
        ),
        migrations.AlterField(
            model_name="label",
            name="is_default",
            field=models.BooleanField(default=False, help_text="是否是默认标签", verbose_name="默认标签"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(db_index=True, help_text="标签名称", max_length=255, verbose_name="标签名称"),
        ),
        migrations.AlterField(
            model_name="label",
            name="project_id",
            field=models.IntegerField(default=-1, help_text="标签对应project id", verbose_name="项目 ID"),
        ),
    ]
