# Generated by Django 3.2.15 on 2022-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0002_auto_20210415_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="label", name="from_space_id", field=models.IntegerField(null=True, verbose_name="来源空间 ID"),
        ),
        migrations.AddField(
            model_name="templatelabelrelation",
            name="template_source",
            field=models.CharField(
                choices=[("project", "项目流程"), ("common", "公共流程"), ("onetime", "一次性任务")],
                default="project",
                max_length=32,
                verbose_name="流程模板来源",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templatelabelrelation", unique_together={("template_id", "label_id", "template_source")},
        ),
    ]
