# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachepackagesource',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='\u5305\u6e90\u8bf4\u660e'),
        ),
    ]
