# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_plugins", "0005_auto_20200325_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3originalsource", name="source_dir", field=models.TextField(default="", verbose_name="源目录名"),
        ),
    ]
