# Generated by Django 4.2 on 2025-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_plugins", "0006_s3originalsource_source_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachepackagesource",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="filesystemoriginalsource",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="gitrepooriginalsource",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="s3originalsource",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="synctask",
            name="tenant_id",
            field=models.CharField(db_index=True, default="default", max_length=64, verbose_name="租户ID"),
        ),
    ]
