# Generated by Django 2.2.24 on 2021-11-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskTmplExecuteTopN",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topn", models.IntegerField(verbose_name="流程执行次数topn统计面板配置")),
            ],
            options={
                "verbose_name": "流程执行次数topn统计面板配置",
                "verbose_name_plural": "流程执行次数topn统计面板配置",
            },
        ),
    ]
