# Generated by Django 2.2.24 on 2021-11-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="TaskflowExecutedNodeStatistics",
            name="is_remote",
            field=models.BooleanField(default=False, verbose_name="是否第三方插件"),
        ),
        migrations.AddField(
            model_name="TemplateNodeStatistics",
            name="is_remote",
            field=models.BooleanField(default=False, verbose_name="是否第三方插件"),
        ),
    ]
