# Generated by Django 2.2.24 on 2021-11-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_statistics", "0002_projectstatisticsdemision_tasktmplexecutetopn"),
        ("analysis_statistics", "0003_auto_20211125_1454"),
    ]

    operations = []
