# Generated by Django 3.2.15 on 2023-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_statistics", "0007_taskflowexecutednodestatistics_template_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskflowexecutednodestatistics",
            name="trigger_template_id",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="触发模版ID，独立子流程根流程 ID"),
        ),
    ]
