# Generated by Django 3.2.15 on 2025-02-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedTaskInstance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="id")),
                ("task_id", models.BigIntegerField(db_index=True, verbose_name="任务 ID")),
                ("project_id", models.BigIntegerField(default=-1, help_text="模板所属项目ID", verbose_name="项目 ID")),
                ("name", models.CharField(default="default_instance", max_length=128, verbose_name="实例名称")),
                ("template_id", models.CharField(max_length=32, verbose_name="Pipeline模板ID")),
                ("task_template_id", models.CharField(max_length=32, verbose_name="Task模板ID")),
                (
                    "template_source",
                    models.CharField(
                        choices=[("project", "项目流程"), ("common", "公共流程"), ("onetime", "一次性任务")],
                        default="project",
                        max_length=32,
                        verbose_name="流程模板来源",
                    ),
                ),
                (
                    "create_method",
                    models.CharField(
                        choices=[
                            ("app", "手动"),
                            ("api", "API网关"),
                            ("app_maker", "轻应用"),
                            ("periodic", "周期任务"),
                            ("clocked", "计划任务"),
                            ("mobile", "移动端"),
                        ],
                        default="app",
                        max_length=30,
                        verbose_name="创建方式",
                    ),
                ),
                (
                    "create_info",
                    models.CharField(blank=True, max_length=255, verbose_name="创建任务额外信息（App maker ID或APP CODE或周期任务ID）"),
                ),
                ("creator", models.CharField(blank=True, max_length=32, verbose_name="创建者")),
                ("create_time", models.DateTimeField(db_index=True, verbose_name="任务创建时间")),
                ("archived_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="任务归档时间")),
                ("executor", models.CharField(blank=True, max_length=32, verbose_name="执行者")),
                (
                    "recorded_executor_proxy",
                    models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name="任务执行人代理"),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="启动时间")),
                ("finish_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("is_started", models.BooleanField(default=False, verbose_name="是否已经启动")),
                ("is_finished", models.BooleanField(default=False, verbose_name="是否已经完成")),
                ("is_revoked", models.BooleanField(default=False, verbose_name="是否已经撤销")),
                ("engine_ver", models.IntegerField(choices=[(1, "v1"), (2, "v2")], default=2, verbose_name="引擎版本")),
                ("is_child_taskflow", models.BooleanField(default=False, verbose_name="是否为子任务")),
                (
                    "snapshot_id",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="实例结构数据，指向实例对应的模板的结构数据"),
                ),
                ("extra_info", models.TextField(blank=True, null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "归档任务实例",
                "verbose_name_plural": "归档任务实例",
                "index_together": {("project_id", "task_template_id")},
            },
        ),
    ]
