# Generated by Django 3.2.15 on 2025-06-12 13:28

from django.db import migrations, models
import gcloud.constants


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_auto_20210319_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="commontemplate",
            name="scope",
            field=models.JSONField(default=gcloud.constants.get_default_scope, verbose_name="公共流程使用范围"),
        ),
    ]
