# Generated by Django 4.2 on 2025-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_auto_20210319_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontemplate',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64, verbose_name='租户ID'),
        ),
    ]
