# Generated by Django 3.2.15 on 2022-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_auto_20210319_1756"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonSpace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="空间名称")),
                ("code", models.CharField(max_length=64, verbose_name="空间代号")),
                ("description", models.TextField(verbose_name="空间说明")),
                ("creator", models.CharField(max_length=255, verbose_name="创建者")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={"verbose_name": "公共流程空间", "verbose_name_plural": "公共流程空间",},
        ),
        migrations.AddField(
            model_name="commontemplate",
            name="space_id",
            field=models.IntegerField(db_index=True, null=True, verbose_name="公共流程空间ID"),
        ),
    ]
