# Generated by Django 3.2.15 on 2025-06-18 01:30

from django.db import migrations, models
import gcloud.common_template.models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_auto_20210319_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="commontemplate",
            name="extra_info",
            field=models.JSONField(
                default=gcloud.common_template.models.get_default_project_scope, verbose_name="额外信息"
            ),
        ),
    ]
