# Generated by Django 4.2.20 on 2026-02-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0009_commontemplate_extra_info"),
        ("template", "0009_commontemplate_tenant_id"),
    ]

    operations = []
