# Generated by Django 4.2.20 on 2026-03-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0010_auto_20260210_0022"),
        ("template", "0010_merge_20260204_0934"),
    ]

    operations = []
