# Generated by Django 3.2.15 on 2024-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateSharedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(default=-1, help_text="项目 ID", verbose_name="项目 ID")),
                ("template_id", models.IntegerField(db_index=True, verbose_name="模版ID")),
                (
                    "template_source",
                    models.CharField(
                        choices=[("project", "项目流程"), ("common", "公共流程"), ("onetime", "一次性任务")],
                        default="project",
                        max_length=32,
                        verbose_name="流程模板来源",
                    ),
                ),
                ("create", models.CharField(help_text="执行者", max_length=128, verbose_name="执行者")),
                ("create_time", models.DateTimeField(auto_now_add=True, help_text="执行时间", verbose_name="执行时间")),
            ],
            options={
                "verbose_name": "模板共享记录 TemplateSharedRecord",
                "verbose_name_plural": "模板共享记录 TemplateSharedRecord",
                "unique_together": {("project_id", "template_id")},
            },
        ),
    ]
