# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodictask', '0004_set_business_to_none'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodictask',
            name='business',
        ),
    ]
