# Generated by Django 3.2.12 on 2022-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodictask", "0007_auto_20200325_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictask",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="创建任务时间"),
        ),
        migrations.AddField(
            model_name="periodictask",
            name="creator",
            field=models.CharField(default="", max_length=32, verbose_name="创建者"),
        ),
        migrations.AddField(
            model_name="periodictask",
            name="edit_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="更新任务时间"),
        ),
        migrations.AddField(
            model_name="periodictask",
            name="editor",
            field=models.CharField(default="", max_length=32, verbose_name="更新者"),
        ),
        migrations.AddField(
            model_name="periodictask",
            name="template_version",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="创建任务时模版 version"),
        ),
    ]
