# Generated by Django 3.2.12 on 2022-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodictask", "0009_sync_periodic_task_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodictask",
            name="template_scheme_ids",
            field=models.TextField(blank=True, null=True, verbose_name="创建任务时模版执行方案id"),
        ),
    ]
