# Generated by Django 3.2.15 on 2024-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateSharedRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(default=-1, help_text="项目 ID", verbose_name="项目 ID")),
                ("template_id", models.IntegerField(db_index=True, help_text="模版 ID", verbose_name="模版 ID")),
                ("creator", models.CharField(help_text="执行者", max_length=128, verbose_name="执行者")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("extra_info", models.TextField(blank=True, null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "模板共享记录 TemplateSharedRecord",
                "verbose_name_plural": "模板共享记录 TemplateSharedRecord",
            },
        ),
    ]
