# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModuleFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=128, verbose_name='file locate ip')),
                ('file_name', models.TextField(verbose_name='file name')),
                ('file_path', models.TextField(verbose_name='file locate path')),
            ],
        ),
    ]
