# Generated by Django 2.2.16 on 2021-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_uploadticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadticket",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="wether this ticket is available"),
        ),
    ]
