# Generated by Django 3.2.15 on 2022-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_bkjobfilecredential_bkjobfilesource"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUploadRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=64, verbose_name="User name")),
                ("file_name", models.TextField(verbose_name="File name")),
                ("file_path", models.TextField(verbose_name="File locate path")),
                ("extra_info", models.TextField(blank=True, null=True, verbose_name="Extra info")),
                ("record_time", models.DateTimeField(auto_now=True, verbose_name="Record time")),
            ],
        ),
    ]
