# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskOperateRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance_id", models.IntegerField(verbose_name="任务实例ID")),
                ("name", models.CharField(max_length=255, verbose_name="任务名")),
                ("node_id", models.IntegerField(verbose_name="任务实例节点ID")),
                ("node_name", models.CharField(max_length=255, verbose_name="任务实例节点名称")),
                ("project", models.CharField(blank=True, default="", max_length=128, verbose_name="所属业务")),
                ("operator", models.CharField(max_length=128, verbose_name="操作人")),
                (
                    "operate_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("create", "创建"),
                            ("delete", "删除"),
                            ("start", "执行"),
                            ("pause", "暂停"),
                            ("resume", "继续"),
                            ("revoke", "撤消"),
                            ("delete", "删除"),
                            ("update", "修改"),
                            ("retry", "重试"),
                            ("skip", "跳过"),
                            ("skip_exg", "跳过失败网关"),
                            ("pause_subproc", "暂停节点"),
                            ("resume_subproc", "继续节点"),
                            ("forced_fail", "强制失败"),
                            ("update", "修改"),
                            ("spec_nodes_timer_reset", "调整时间"),
                        ],
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                ("operate_date", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "operate_source",
                    models.CharField(choices=[("WEB", "web 端"), ("API", "api 接口")], max_length=64, verbose_name="操作来源"),
                ),
            ],
            options={
                "verbose_name": "任务操作记录",
                "verbose_name_plural": "任务操作记录",
            },
        ),
        migrations.CreateModel(
            name="TemplateOperateRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance_id", models.IntegerField(verbose_name="模版ID")),
                ("name", models.CharField(max_length=255, verbose_name="模版名称")),
                ("project", models.CharField(blank=True, default="", max_length=128, verbose_name="所属业务")),
                ("operator", models.CharField(max_length=128, verbose_name="操作人")),
                (
                    "operate_type",
                    models.CharField(
                        choices=[("none", "None"), ("create", "创建"), ("delete", "删除"), ("update", "修改")],
                        max_length=64,
                        verbose_name="操作类型",
                    ),
                ),
                ("operate_date", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "operate_source",
                    models.CharField(
                        choices=[("project", "项目流程"), ("common", "公共流程"), ("onetime", "一次性任务")],
                        max_length=64,
                        verbose_name="操作来源",
                    ),
                ),
            ],
            options={
                "verbose_name": "模版操作记录",
                "verbose_name_plural": "模版操作记录",
            },
        ),
    ]
