# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operate_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskoperaterecord",
            name="node_id",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="任务实例节点ID"),
        ),
        migrations.AlterField(
            model_name="taskoperaterecord",
            name="node_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="任务实例节点名称"),
        ),
    ]
