# Generated by Django 2.2.16 on 2021-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operate_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskoperaterecord",
            name="operate_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("create", "创建"),
                    ("task_clone", "克隆(创建)"),
                    ("start", "执行"),
                    ("pause", "暂停"),
                    ("resume", "继续"),
                    ("revoke", "撤消"),
                    ("delete", "删除"),
                    ("update", "修改"),
                    ("callback", "回调"),
                    ("retry", "重试"),
                    ("skip", "跳过"),
                    ("skip_exg", "跳过失败网关"),
                    ("skip_cpg", "跳过并行条件网关"),
                    ("pause_subproc", "暂停节点"),
                    ("resume_subproc", "继续节点"),
                    ("forced_fail", "强制失败"),
                    ("spec_nodes_timer_reset", "调整时间"),
                    ("task_action", "任务操作"),
                    ("nodes_action", "节点操作"),
                ],
                max_length=64,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="templateoperaterecord",
            name="operate_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("create", "创建"),
                    ("task_clone", "克隆(创建)"),
                    ("start", "执行"),
                    ("pause", "暂停"),
                    ("resume", "继续"),
                    ("revoke", "撤消"),
                    ("delete", "删除"),
                    ("update", "修改"),
                    ("callback", "回调"),
                    ("retry", "重试"),
                    ("skip", "跳过"),
                    ("skip_exg", "跳过失败网关"),
                    ("skip_cpg", "跳过并行条件网关"),
                    ("pause_subproc", "暂停节点"),
                    ("resume_subproc", "继续节点"),
                    ("forced_fail", "强制失败"),
                    ("spec_nodes_timer_reset", "调整时间"),
                    ("task_action", "任务操作"),
                    ("nodes_action", "节点操作"),
                ],
                max_length=64,
                verbose_name="操作类型",
            ),
        ),
    ]
