# Generated by Django 3.2.15 on 2022-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operate_record", "0002_auto_20210827_0140"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskoperaterecord",
            name="extra_info",
            field=models.TextField(blank=True, default="", verbose_name="任务实例节点拓展信息"),
        ),
    ]
