# Generated by Django 4.2.17 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operate_record", "0003_taskoperaterecord_extra_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskoperaterecord",
            name="operate_source",
            field=models.CharField(
                choices=[
                    ("app", "app 页面"),
                    ("api", "api 接口"),
                    ("parent", "父任务"),
                    ("project", "项目流程"),
                    ("common", "公共流程"),
                    ("onetime", "一次性任务"),
                ],
                max_length=64,
                verbose_name="操作来源",
            ),
        ),
        migrations.AlterField(
            model_name="templateoperaterecord",
            name="operate_source",
            field=models.CharField(
                choices=[
                    ("app", "app 页面"),
                    ("api", "api 接口"),
                    ("parent", "父任务"),
                    ("project", "项目流程"),
                    ("common", "公共流程"),
                    ("onetime", "一次性任务"),
                ],
                max_length=64,
                verbose_name="操作来源",
            ),
        ),
    ]
