# Generated by Django 3.2.25 on 2026-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_gateway", "0002_callback_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugingatewayrun",
            name="execution_expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plugingatewayrun",
            name="runtime_outputs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plugingatewayrun",
            name="schedule_times",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plugingatewaysourceconfig",
            name="do_not_open_list",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="plugingatewaysourceconfig",
            name="execution_timeout_seconds",
            field=models.IntegerField(default=7200),
        ),
        migrations.AddField(
            model_name="plugingatewaysourceconfig",
            name="scope_project_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
