# Generated by Django 3.2.25 on 2026-07-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin_gateway", "0003_full_capability_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugingatewaysourceconfig",
            name="plugin_allow_list",
        ),
    ]
