# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190612_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='\u7528\u6237\u540d')),
                ('count', models.IntegerField(default=1, verbose_name='\u9879\u76ee\u8bbf\u95ee\u6b21\u6570')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='\u7528\u6237\u9ed8\u8ba4\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bbf\u95ee\u9879\u76ee\u8ba1\u6570 ProjectCounter',
                'verbose_name_plural': '\u7528\u6237\u8bbf\u95ee\u9879\u76ee\u8ba1\u6570 ProjectCounter',
            },
        ),
    ]
