# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_admin_init'),
        ('core', '0013_projectcounter'),
    ]

    operations = [
    ]
