# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20200325_1458"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(verbose_name="项目 ID")),
                ("executor_proxy", models.CharField(default="", max_length=255, verbose_name="任务执行人代理")),
                ("executor_proxy_exempts", models.TextField(default="", verbose_name="不使用执行人代理的用户列表")),
            ],
            options={"verbose_name": "项目配置 ProjectConfig", "verbose_name_plural": "项目配置 ProjectConfig",},
        ),
    ]
