# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-10 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20200325_1458"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBasedComponent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("component_code", models.CharField(max_length=255, verbose_name="组件编码")),
                ("project_id", models.CharField(max_length=64, verbose_name="项目id")),
            ],
            options={
                "verbose_name": "基于项目的组件 ProjectBasedComponent",
                "verbose_name_plural": "基于项目的组件 ProjectBasedComponent",
            },
        ),
    ]
