# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_projectconfig"),
        ("core", "0016_projectbasedcomponent"),
    ]

    operations = []
