# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-24 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20200812_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分组名称')),
                ('members', models.TextField(blank=True, default='', help_text='多个成员以英文,分隔', null=True, verbose_name='分组成员')),
            ],
            options={
                'verbose_name': '人员分组设置 StaffGroupSet',
                'verbose_name_plural': '人员分组设置 StaffGroupSet',
            },
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='executor_proxy',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='任务执行人代理'),
        ),
        migrations.AlterField(
            model_name='projectconfig',
            name='executor_proxy_exempts',
            field=models.TextField(blank=True, default='', verbose_name='不使用执行人代理的用户列表'),
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='staff_groups',
            field=models.ManyToManyField(blank=True, to='core.StaffGroupSet', verbose_name='人员分组'),
        ),
    ]
