# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20200812_1756"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_id", models.IntegerField(verbose_name="项目 ID")),
                ("name", models.CharField(help_text="每个项目下的配置名称要保证唯一", max_length=255, verbose_name="配置名称")),
                (
                    "config_type",
                    models.CharField(
                        choices=[("set", "集群筛选配置"), ("host", "主机筛选配置")], max_length=255, verbose_name="配置类型"
                    ),
                ),
                ("creator", models.CharField(blank=True, max_length=255, null=True, verbose_name="创建者")),
                ("data", models.TextField(default="{}", verbose_name="筛选配置参数")),
                ("create_time", models.DateTimeField(auto_now_add=True, null=True, verbose_name="最近编辑时间")),
            ],
            options={"verbose_name": "集群资源筛选方案", "verbose_name_plural": "集群资源筛选方案", "ordering": ["-id"],},
        ),
        migrations.AlterField(
            model_name="projectconfig",
            name="executor_proxy",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="任务执行人代理"),
        ),
        migrations.AlterField(
            model_name="projectconfig",
            name="executor_proxy_exempts",
            field=models.TextField(blank=True, default="", verbose_name="不使用执行人代理的用户列表"),
        ),
        migrations.AlterUniqueTogether(
            name="resourceconfig", unique_together=set([("project_id", "name", "config_type")]),
        ),
    ]
