# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-31 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20200828_1647"),
        ("core", "0018_auto_20200824_1526"),
    ]

    operations = []
