# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_merge_20200831_1807"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectconfig",
            name="staff_groups",
        ),
        migrations.AddField(
            model_name="staffgroupset",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AddField(
            model_name="staffgroupset",
            name="project_id",
            field=models.IntegerField(default=0, verbose_name="项目 ID"),
        ),
        migrations.AlterField(
            model_name="staffgroupset",
            name="name",
            field=models.CharField(help_text="同项目下名称唯一", max_length=255, verbose_name="分组名称"),
        ),
    ]
