# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200908_2030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="name", field=models.CharField(max_length=192, verbose_name="项目名"),
        ),
        migrations.AlterUniqueTogether(name="project", unique_together=set([("bk_biz_id", "name")]),),
    ]
