# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-27 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200908_2030"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="project", unique_together=set([("bk_biz_id", "name")]),),
    ]
