# Generated by Django 2.2.6 on 2021-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200908_2030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "permissions": (("get_business", "Can get business"), ("manage_business", "Can manage business")),
                "verbose_name": "业务 Business",
                "verbose_name_plural": "业务 Business",
            },
        ),
        migrations.AlterField(
            model_name="staffgroupset", name="name", field=models.CharField(max_length=255, verbose_name="分组名称"),
        ),
        migrations.AlterField(
            model_name="staffgroupset", name="project_id", field=models.IntegerField(verbose_name="项目 ID"),
        ),
    ]
