# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200908_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfig",
            name="max_periodic_task_num",
            field=models.IntegerField(blank=True, default=-1, verbose_name="项目下最大周期任务数"),
        ),
        migrations.AlterField(
            model_name="staffgroupset", name="name", field=models.CharField(max_length=255, verbose_name="分组名称"),
        ),
        migrations.AlterField(
            model_name="staffgroupset", name="project_id", field=models.IntegerField(verbose_name="项目 ID"),
        ),
    ]
