# Generated by Django 2.2.6 on 2021-03-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20210219_1936"),
        ("core", "0021_auto_20210125_1943"),
    ]

    operations = []
