# Generated by Django 2.2.6 on 2021-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20210125_1943"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_id", models.IntegerField(verbose_name="范围对象ID")),
                ("scope", models.IntegerField(choices=[(1, "project"), (2, "template")], verbose_name="配置范围")),
                ("engine_ver", models.IntegerField(choices=[(1, "v1"), (2, "v2")], verbose_name="引擎版本")),
            ],
            options={
                "verbose_name": "引擎版本配置 ProjectConfig",
                "verbose_name_plural": "引擎版本配置 ProjectConfig",
                "index_together": {("scope", "scope_id")},
            },
        ),
    ]
