# Generated by Django 2.2.6 on 2021-04-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_merge_20210326_1511"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="project", unique_together={("bk_biz_id", "name")},),
    ]
