# Generated by Django 2.2.6 on 2021-04-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_merge_20210326_1511"),
        ("core", "0021_auto_20210427_1455"),
    ]

    operations = []
