# Generated by Django 2.2.16 on 2021-06-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_merge_20210428_1450"),
        ("core", "0023_merge_20210408_1926"),
    ]

    operations = []
