# Generated by Django 2.2.16 on 2021-07-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_merge_20210602_1455"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="engineconfig",
            options={"verbose_name": "引擎版本配置 EngineConfig", "verbose_name_plural": "引擎版本配置 EngineConfig"},
        ),
    ]
