# Generated by Django 3.2.15 on 2023-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20210602_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineconfig',
            options={'verbose_name': '引擎版本配置 EngineConfig', 'verbose_name_plural': '引擎版本配置 EngineConfig'},
        ),
        migrations.CreateModel(
            name='DisabledComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=255, verbose_name='组件编码')),
                ('action', models.CharField(choices=[('list', 'list'), ('retrieve', 'retrieve'), ('all', 'all')], max_length=32, verbose_name='禁用动作')),
                ('scope', models.CharField(choices=[('task', '任务'), ('flow', '流程'), ('all', '全部')], max_length=32, verbose_name='禁用范围')),
            ],
            options={
                'verbose_name': '全局禁用的组件 DisabledComponent',
                'verbose_name_plural': '全局禁用的组件 DisabledComponent',
                'index_together': {('scope', 'action')},
            },
        ),
    ]
