# Generated by Django 3.2.15 on 2022-12-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_merge_20210602_1455"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="engineconfig",
            options={"verbose_name": "引擎版本配置 EngineConfig", "verbose_name_plural": "引擎版本配置 EngineConfig"},
        ),
        migrations.CreateModel(
            name="UserFavoriteProject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=128, verbose_name="用户名")),
                ("project_id", models.IntegerField(verbose_name="项目id")),
            ],
            options={
                "verbose_name": "用户收藏项目 UserFavoriteProject",
                "verbose_name_plural": "用户收藏项目 UserFavoriteProject",
                "unique_together": {("username", "project_id")},
            },
        ),
    ]
