# Generated by Django 3.2.25 on 2025-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20230609_2101"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfig",
            name="task_clean_configs",
            field=models.JSONField(blank=True, default=dict, verbose_name="任务清理扩展配置"),
        ),
    ]
