# Generated by Django 3.2.15 on 2025-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20230609_2101"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppExemption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_code", models.CharField(max_length=32, unique=True, verbose_name="应用code")),
                ("exemption_projects", models.CharField(max_length=255, verbose_name="豁免项目 ID 列表")),
                ("extra_info", models.JSONField(blank=True, null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "应用豁免 AppExemption",
                "verbose_name_plural": "应用豁免 AppExemption",
            },
        ),
    ]
