# Generated by Django 3.2.15 on 2023-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20230609_2101"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfig",
            name="allow_plugin_cross_biz",
            field=models.BooleanField(default=False, verbose_name="支持模板插件中选择业务"),
        ),
    ]
