# Generated by Django 3.2.25 on 2025-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_projectconfig_task_clean_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfig",
            name="custom_display_configs",
            field=models.JSONField(blank=True, default=dict, verbose_name="自定义显示配置"),
        ),
    ]
