# Generated by Django 4.2.20 on 2026-02-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_business_tenant_id_project_tenant_id"),
        ("core", "0027_projectconfig_custom_display_configs"),
    ]

    operations = []
