# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_userdefaultproject'),
        ('appmaker', '0005_auto_20180823_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmaker',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
