# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-17 08:32
from __future__ import unicode_literals

from django.db import migrations


def reverse_func(apps, schema_editor):
    AppMaker = apps.get_model('appmaker', 'AppMaker')
    db_alias = schema_editor.connection.alias
    AppMaker.objects.using(db_alias).all().update(project=None)


def forward_func(apps, schema_editor):
    AppMaker = apps.get_model('appmaker', 'AppMaker')
    Project = apps.get_model('core', 'Project')
    db_alias = schema_editor.connection.alias

    projects = Project.objects.filter(from_cmdb=True)
    cc_id_to_project = {proj.cmdb_biz_id: proj for proj in projects}
    apps = AppMaker.objects.using(db_alias).all()

    instance_count = len(apps)
    print('')
    for i, app in enumerate(apps, start=1):
        app.project = cc_id_to_project[app.business.cc_id]
        app.save()
        print("AppMaker project relationship build: (%s/%s)" % (i, instance_count))


class Migration(migrations.Migration):
    dependencies = [
        ('appmaker', '0006_appmaker_project'),
        ('core', '0011_create_project_for_exist_biz'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
