# Generated by Django 4.2.17 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmaker", "0011_appmaker_new_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmaker",
            name="category",
            field=models.CharField(
                choices=[
                    ("OpsTools", "运维工具"),
                    ("MonitorAlarm", "监控告警"),
                    ("ConfManage", "配置管理"),
                    ("DevTools", "开发工具"),
                    ("EnterpriseIT", "企业IT"),
                    ("OfficeApp", "办公应用"),
                    ("Other", "其它"),
                    ("Default", "默认分类"),
                ],
                max_length=255,
                verbose_name="模板类型",
            ),
        ),
    ]
