# Generated by Django 3.2.15 on 2024-01-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmaker", "0011_appmaker_new_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmaker",
            name="desc",
            field=models.CharField(max_length=500, null=True, verbose_name="APP描述信息"),
        ),
    ]
